# Generated by Django 3.2.6 on 2021-08-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financiera.base')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('IDV', 'Donante individual'), ('IFM', 'Donante institucional - Fondo de mujeres'), ('IFP', 'Donante institucional - Fundación privada'), ('IIB', 'Donante institucional - Institución bilateral'), ('IIM', 'Donante institucional - Institución multilateral'), ('IOG', 'Donante institucional - ONG'), ('CEP', 'Donante corporativo - Empresa privada'), ('CGR', 'Donante corporativo - Gremio'), ('COT', 'Donante corporativo - Otro')], max_length=3, null=True)),
                ('fecha_init_fcam', models.DateField(null=True, verbose_name='Fecha que empezó su relación con el FCAM')),
                ('estatus', models.CharField(choices=[('ACT', 'Actual'), ('PAS', 'Pasado'), ('POT', 'Potencial')], max_length=3, null=True)),
                ('pais', models.CharField(max_length=255, null=True, verbose_name='País de origen')),
                ('direccion', models.TextField(null=True, verbose_name='Dirección')),
                ('sitio_web', models.URLField(null=True, verbose_name='Sitio web')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('comentarios', models.TextField(null=True, verbose_name='Comentartios')),
            ],
            bases=('financiera.base',),
        ),
        migrations.CreateModel(
            name='DistribucionIngresoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto')),
                ('programa', models.CharField(choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, null=True, verbose_name='Programa')),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionIngresoIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto')),
                ('ic', models.CharField(choices=[('SCA', 'Socias en Centroamérica'), ('FCA', 'Socias fuera de Centroamérica'), ('RFM', 'Redes y fondos de mujeres'), ('RRC', 'Respuesta Rápida en Centroamérica'), ('RRF', 'Respuesta Rápida fuera de Centroamérica'), ('OTR', 'Otros')], max_length=3, null=True, verbose_name='Programa')),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionIngresoApoyoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto')),
                ('programa', models.BooleanField(null=True, verbose_name='Apoyo estratégico')),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financiera.base')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre del proyecto')),
                ('tipo', models.CharField(choices=[('SPG', 'Soporte general'), ('PRO', 'Proyecto'), ('ICG', ' Iniciativa Conjunta Soporte General'), ('ICP', 'Iniciativa Conjunta Proyecto')], max_length=3, null=True)),
                ('ic_apoya', models.CharField(choices=[('IC1', 'INICIATIVA-3'), ('IC2', 'GAGGA'), ('IC3', 'IMDEFENSORAS')], max_length=3, null=True)),
                ('mecanismo', models.CharField(choices=[('CAM', 'Campaña'), ('DES', 'Donación en especie'), ('PAT', 'Patrocinio fiscal'), ('DLR', 'Donación en línea regular'), ('DLP', 'Donación en línea puntual'), ('DEF', 'Donación en efectivo'), ('OTR', 'Otros')], max_length=3, null=True)),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha del ingreso')),
                ('fecha_init', models.DateField(null=True, verbose_name='Fecha del inicio')),
                ('fecha_finit', models.DateField(null=True, verbose_name='Fecha de finalización')),
                ('monto_total_EUR', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto total USD')),
                ('tipo_de_cambio_EUR_USD', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tipo de cambio (EUR -> USD)')),
                ('monto_total_USD', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto total para Iniciativas conjuntas')),
                ('donante_fuente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiera.donante')),
            ],
            bases=('financiera.base',),
        ),
    ]
