# Generated by Django 3.2.6 on 2021-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0002_auto_20210816_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucioningresoapoyoestrategico',
            name='programa',
            field=models.BooleanField(default=False, verbose_name='Apoyo estratégico'),
        ),
    ]
