# Generated by Django 3.2.6 on 2021-08-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0042_auto_20210824_1350'),
        ('financiera', '0003_alter_distribucioningresoapoyoestrategico_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='codigo',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='apoyo_estrategico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.apoyoestrategico'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='estatus',
            field=models.CharField(blank=True, choices=[('COP', 'Coparte'), ('APE', 'Apoyo Estratégico'), ('ICJ', 'Iniciativa conjunta')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='fecha_proyectada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha proyectada de desembolso'),
        ),
        migrations.RemoveField(
            model_name='desembolso',
            name='ingreso_vinculado',
        ),
        migrations.AddField(
            model_name='desembolso',
            name='ingreso_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiera.ingreso'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='iniciativa_conjunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.iniciativaconjunta'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='monto_total_EUR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Monto total EUR'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='monto_total_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Monto total USD'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='numero_desembolso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.coparte'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='tipo_de_cambio_EUR_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Tipo de cambio (EUR -> USD)'),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='tipo_org',
            field=models.CharField(blank=True, choices=[('COP', 'Coparte'), ('APE', 'Apoyo Estratégico'), ('ICJ', 'Iniciativa conjunta')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='total_desembolsos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribucioningresoapoyoestrategico',
            name='programa',
            field=models.BooleanField(blank=True, default=False, verbose_name='Apoyo estratégico'),
        ),
        migrations.AlterField(
            model_name='distribucioningresoic',
            name='ic',
            field=models.CharField(blank=True, choices=[('SCA', 'Socias en Centroamérica'), ('FCA', 'Socias fuera de Centroamérica'), ('RFM', 'Redes y fondos de mujeres'), ('RRC', 'Respuesta Rápida en Centroamérica'), ('RRF', 'Respuesta Rápida fuera de Centroamérica'), ('OTR', 'Otros')], max_length=3, null=True, verbose_name='Iniciativa conjunta'),
        ),
        migrations.AlterField(
            model_name='distribucioningresoprograma',
            name='programa',
            field=models.CharField(blank=True, choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, null=True, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='estatus',
            field=models.CharField(blank=True, choices=[('ACT', 'Actual'), ('PAS', 'Pasado'), ('POT', 'Potencial')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='fecha_init_fcam',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha que empezó su relación con el FCAM'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_finit',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_init',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del inicio'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ic_apoya',
            field=models.CharField(blank=True, choices=[('IC1', 'INICIATIVA-3'), ('IC2', 'GAGGA'), ('IC3', 'IMDEFENSORAS')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='mecanismo',
            field=models.CharField(blank=True, choices=[('CAM', 'Campaña'), ('DES', 'Donación en especie'), ('PAT', 'Patrocinio fiscal'), ('DLR', 'Donación en línea regular'), ('DLP', 'Donación en línea puntual'), ('DEF', 'Donación en efectivo'), ('OTR', 'Otros')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto_total_EUR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Monto total USD'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto_total_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Monto total para Iniciativas conjuntas'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SPG', 'Soporte general'), ('PRO', 'Proyecto'), ('ICG', ' Iniciativa Conjunta Soporte General'), ('ICP', 'Iniciativa Conjunta Proyecto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_de_cambio_EUR_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Tipo de cambio (EUR -> USD)'),
        ),
    ]
