# Generated by Django 3.2.6 on 2021-08-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0004_auto_20210830_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolso',
            name='estatus',
            field=models.CharField(blank=True, choices=[('COP', 'Coparte'), ('APE', 'Apoyo estratégico'), ('ICJ', 'Iniciativa conjunta')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='tipo_org',
            field=models.CharField(blank=True, choices=[('COP', 'Coparte'), ('APE', 'Apoyo estratégico'), ('ICJ', 'Iniciativa conjunta')], max_length=3, null=True),
        ),
    ]
