# Generated by Django 3.2.6 on 2021-08-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0042_auto_20210824_1350'),
        ('financiera', '0006_remove_distribucioningresoapoyoestrategico_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolso',
            name='estatus',
            field=models.CharField(blank=True, choices=[('REA', 'Realizado'), ('PEN', 'Pendiente'), ('ANU', 'Anulado')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='desembolso',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.propuesta'),
        ),
    ]
