# Generated by Django 3.2.6 on 2021-08-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='coparte',
            name='fecha_personeria',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coparte',
            name='informacion_bancaria',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coparte',
            name='personeria',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='telefono',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='coparte',
            name='contacto',
            field=models.ManyToManyField(to='programa.Contacto'),
        ),
    ]
