# Generated by Django 3.2.6 on 2021-08-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_rename_contacto_coparte_contactos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coparte',
            name='contactos',
        ),
        migrations.AddField(
            model_name='contacto',
            name='organizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.coparte'),
        ),
    ]
