# Generated by Django 3.2.6 on 2021-08-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programa', '0004_auto_20210806_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coparte',
            name='startDate',
        ),
        migrations.AddField(
            model_name='coparte',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
