# Generated by Django 3.2.6 on 2021-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_auto_20210809_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coparte',
            name='codigo_org',
            field=models.CharField(max_length=7, verbose_name='Código de organización'),
        ),
    ]
