# Generated by Django 3.2.6 on 2021-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0009_auto_20210812_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativaconjunta',
            name='participa_ic',
            field=models.CharField(choices=[('IC1', 'INICIATIVA-3'), ('IC2', 'GAGGA'), ('IC3', 'IMDEFENSORAS')], max_length=3, null=True, verbose_name='Iniciativa conjunta en la que participa'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='tipo_ic',
            field=models.CharField(choices=[('SCA', 'Socias en Centroamérica'), ('FCA', 'Socias fuera de Centroamérica'), ('RFM', 'Redes y fondos de mujeres'), ('RRC', 'Respuesta Rápida en Centroamérica'), ('RRF', 'Respuesta Rápida fuera de Centroamérica'), ('OTR', 'Otros')], max_length=3, null=True, verbose_name='Tipo de iniciaptiva conjunta'),
        ),
    ]
