# Generated by Django 3.2.6 on 2021-08-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programa', '0010_auto_20210812_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3)),
                ('codigo_org', models.CharField(max_length=7, verbose_name='Código de organización')),
                ('nombre_org', models.CharField(max_length=255)),
                ('estatus_org', models.CharField(choices=[('ACT', 'Activo'), ('TER', 'Terminado')], default='ACT', max_length=3)),
                ('sello_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sello_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateField(null=True)),
                ('municipio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sitio_web', models.CharField(max_length=255)),
                ('fecha_grupo', models.DateField(null=True)),
                ('tipo_donativo', models.CharField(choices=[('FRE', 'Fondos de Respuesta a Emergencias'), ('AEP', 'Apoyos Estratégicos Puntuales')], max_length=3, null=True, verbose_name='Tipo de donativo')),
                ('fondo_resp_emer', models.CharField(choices=[('APE', 'Apoyo de emergencia a organizaciones, redes y articulaciones'), ('CLD', 'Cambios legislativos que afectan derechos de las mujeres'), ('PDD', 'Protección a defensoras de derechos humanos'), ('RDN', 'Respuesta ante desastres naturales')], max_length=3, null=True, verbose_name='Fondos de Respuesta a Emergencias')),
                ('apoyos_estra_punt', models.CharField(choices=[('AOC', 'Apoyo a organizaciones en crisis financiera'), ('BEV', 'Becas para eventos'), ('DOP', 'Donativos patrocinados'), ('PEP', 'Proyectos estratégicos puntuales')], max_length=3, null=True, verbose_name='Apoyos Estratégicos Puntuales')),
                ('tipo_org', models.CharField(choices=[('DOP', 'Grupos intermedios'), ('PEP', 'Fondos'), ('AOC', 'INGO/ONG internacional'), ('BEV', 'Grupo o colectivo de base'), ('BEV', 'Redes'), ('AOC', 'Defensora de derechos humanos'), ('PEP', 'Organizaciones grandes')], max_length=3, null=True, verbose_name='Tipo de organización')),
                ('ano_donativo', models.CharField(choices=[('2021', '2021'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022')], max_length=4, null=True, verbose_name='Año del donativo')),
                ('monto_entregado_USD', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_entregado_EUR', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_de_cambio_EUR_USD', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supervisora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
