# Generated by Django 3.2.6 on 2021-08-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('programa', '0011_apoyoestrategico_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupoactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prop', models.CharField(max_length=7, verbose_name='Código de la propuesta')),
                ('duracion_prop', models.CharField(choices=[('12M', '12 Meses'), ('18M', '18 Meses'), ('24M', '24 Meses'), ('36M', '36 Meses')], max_length=3, null=True, verbose_name='Duración de la propuesta')),
                ('pais', models.CharField(choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3, verbose_name='País')),
                ('tipo_colab', models.CharField(choices=[('ANU', 'Anual'), ('MAN', 'Multianual')], max_length=3, null=True, verbose_name='Tipo de colaboración')),
                ('fondos_prop', models.CharField(choices=[('ANU', 'Anual'), ('MAN', 'Multianual')], max_length=3, null=True, verbose_name='Fondos asignados a la propuestas')),
                ('estatus_prop', models.CharField(choices=[('ENR', 'En revisión'), ('APR', 'Aprobado'), ('VCM', 'Ver Comentarios')], default='ACT', max_length=3, verbose_name='Estatus')),
                ('fecha_aprobacion', models.DateField(null=True, verbose_name='Fecha de aprobación')),
                ('programa', models.CharField(choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, verbose_name='Programa')),
                ('ano_convocatoria', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, verbose_name='Año de la convocatoria')),
                ('nombre_prop', models.CharField(max_length=255, verbose_name='Nombre de la propuesta')),
                ('fecha_entrega', models.DateField(null=True, verbose_name='Fecha de entrega de la propuesta')),
                ('codigo_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.coparte')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponsable_prop', to=settings.AUTH_USER_MODEL)),
                ('supervisora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisora_prop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='ano_donativo',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año del donativo'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='apoyos_estra_punt',
            field=models.CharField(choices=[('BEV', 'Becas para eventos'), ('PEP', 'Proyectos estratégicos puntuales'), ('AOC', 'Apoyo a organizaciones en crisis financiera'), ('DOP', 'Donativos patrocinados')], max_length=3, null=True, verbose_name='Apoyos Estratégicos Puntuales'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fondo_resp_emer',
            field=models.CharField(choices=[('PDD', 'Protección a defensoras de derechos humanos'), ('APE', 'Apoyo de emergencia a organizaciones, redes y articulaciones'), ('RDN', 'Respuesta ante desastres naturales'), ('CLD', 'Cambios legislativos que afectan derechos de las mujeres')], max_length=3, null=True, verbose_name='Fondos de Respuesta a Emergencias'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='tipo_org',
            field=models.CharField(choices=[('BEV', 'Grupo o colectivo de base'), ('PEP', 'Organizaciones grandes'), ('AOC', 'INGO/ONG internacional'), ('DOP', 'Grupos intermedios'), ('BEV', 'Redes'), ('PEP', 'Fondos'), ('AOC', 'Defensora de derechos humanos')], max_length=3, null=True, verbose_name='Tipo de organización'),
        ),
    ]
