# Generated by Django 3.2.6 on 2021-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0012_auto_20210813_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='presupuesto_aprobado_finan_EUR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto aprobado por Gestión Financiera (EUR)'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='presupuesto_aprobado_finan_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto aprobado por Gestión Financiera (USD)'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='presupuesto_aprobado_super_EUR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto aprobado por Supervisora FCAM (EUR)'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='presupuesto_aprobado_super_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Presupuesto aprobado por Supervisora FCAM (USD)'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='tipo_de_cambio_EUR_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tipo de cambio (EUR -> USD)'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='monto_entregado_EUR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='monto_entregado_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='tipo_de_cambio_EUR_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tipo de cambio (EUR -> USD)'),
        ),
    ]
