# Generated by Django 3.2.6 on 2021-08-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programa', '0014_auto_20210816_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeintermedio',
            name='ano',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='codigo_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.coparte'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='codigo_prop',
            field=models.CharField(max_length=7, null=True, verbose_name='Código de la propuesta'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='estatus_prop',
            field=models.CharField(choices=[('ENR', 'En revisión'), ('APR', 'Aprobado'), ('VCM', 'Ver Comentarios')], default='ACT', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='fecha_entrega',
            field=models.DateField(null=True, verbose_name='Fecha de entrega de la propuesta'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='nombre_prop',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de la propuesta'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informeintermedio_reponsable_propu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='supervisora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informeintermedio_supervisora_propu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='codigo_prop',
            field=models.CharField(max_length=7, null=True, verbose_name='Código de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='nombre_prop',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuesta_reponsable_propu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='supervisora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuesta_supervisora_propu', to=settings.AUTH_USER_MODEL),
        ),
    ]
