# Generated by Django 3.2.6 on 2021-08-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0019_informeic_propuestaic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informeic',
            old_name='codigo_prop',
            new_name='codigo_inf_ic',
        ),
        migrations.RenameField(
            model_name='propuestaic',
            old_name='codigo_prop',
            new_name='codigo_prop_ic',
        ),
    ]
