# Generated by Django 3.2.6 on 2021-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0024_contacto_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='direccion',
            field=models.TextField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='estatus_org',
            field=models.CharField(choices=[('ACT', 'Activo'), ('TER', 'Terminado')], default='ACT', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fecha_completado',
            field=models.DateField(null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fecha_grupo',
            field=models.DateField(null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='nombre_org',
            field=models.CharField(max_length=255, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='pais',
            field=models.CharField(choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='telefono',
            field=models.CharField(max_length=60, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='direccion',
            field=models.TextField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='estatus_org',
            field=models.CharField(choices=[('ACT', 'Activo'), ('TER', 'Terminado')], default='ACT', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_completado',
            field=models.DateField(null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_grupo',
            field=models.DateField(null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_personeria',
            field=models.DateField(null=True, verbose_name='Fecha de obtención de personería jurídica'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='informacion_bancaria',
            field=models.TextField(null=True, verbose_name='Información bancaria'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='nombre_org',
            field=models.CharField(max_length=255, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='pais',
            field=models.CharField(choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='personeria',
            field=models.BooleanField(null=True, verbose_name='Cuenta con personería jurídica'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='telefono',
            field=models.CharField(max_length=60, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='direccion',
            field=models.TextField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='estatus_org',
            field=models.CharField(choices=[('ACT', 'Activo'), ('TER', 'Terminado')], default='ACT', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_completado',
            field=models.DateField(null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_grupo',
            field=models.DateField(null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_personeria',
            field=models.DateField(null=True, verbose_name='Fecha de obtención de personería jurídica'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='informacion_bancaria',
            field=models.TextField(null=True, verbose_name='Información bancaria'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='nombre_org',
            field=models.CharField(max_length=255, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='pais',
            field=models.CharField(choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='personeria',
            field=models.BooleanField(null=True, verbose_name='Cuenta con personería jurídica'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='telefono',
            field=models.CharField(max_length=60, verbose_name='Teléfono'),
        ),
    ]
