# Generated by Django 3.2.6 on 2021-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0027_auto_20210818_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefinal',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AddField(
            model_name='informefinal',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='codigo_org',
            field=models.CharField(max_length=7, unique=True, verbose_name='Código de organización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='codigo_org',
            field=models.CharField(max_length=7, unique=True, verbose_name='Código de organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='codigo_org',
            field=models.CharField(max_length=7, unique=True, verbose_name='Código de organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='fondos_prop',
            field=models.CharField(choices=[('SOP', 'Soporte general'), ('APG', 'Apoyo para proyectos')], max_length=3, null=True, verbose_name='Fondos asignados a la propuestas'),
        ),
    ]
