# Generated by Django 3.2.6 on 2021-08-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0028_auto_20210819_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='tipo_colab',
        ),
    ]
