# Generated by Django 3.2.6 on 2021-08-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0029_remove_propuesta_tipo_colab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informefinal',
            name='codigo_prop',
        ),
        migrations.RemoveField(
            model_name='informeintermedio',
            name='codigo_prop',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='codigo_prop',
        ),
        migrations.AddField(
            model_name='informefinal',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='informeintermedio',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='codigo',
            field=models.CharField(max_length=30, null=True, verbose_name='Código'),
        ),
    ]
