# Generated by Django 3.2.6 on 2021-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0032_auto_20210819_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='direccion',
            field=models.TextField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fecha_grupo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='municipio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='nombre_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='telefono',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='direccion',
            field=models.TextField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_grupo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='fecha_personeria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de obtención de personería jurídica'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='informacion_bancaria',
            field=models.TextField(blank=True, null=True, verbose_name='Información bancaria'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='municipio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='nombre_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='personeria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cuenta con personería jurídica'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='telefono',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='direccion',
            field=models.TextField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicial en que se completó la ficha'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_grupo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de conformación del grupo u organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='fecha_personeria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de obtención de personería jurídica'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='informacion_bancaria',
            field=models.TextField(blank=True, null=True, verbose_name='Información bancaria'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='municipio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='nombre_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='personeria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cuenta con personería jurídica'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='telefono',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono'),
        ),
    ]
