# Generated by Django 3.2.6 on 2021-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0033_auto_20210820_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
