# Generated by Django 3.2.6 on 2021-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0034_auto_20210820_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informefinal',
            name='ano',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='informefinal',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de la propuesta'),
        ),
        migrations.AlterField(
            model_name='informefinal',
            name='nombre_prop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la propuesta'),
        ),
        migrations.AlterField(
            model_name='informeintermedio',
            name='ano',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='informeintermedio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de la propuesta'),
        ),
        migrations.AlterField(
            model_name='informeintermedio',
            name='nombre_prop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='ano',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='duracion_prop',
            field=models.CharField(blank=True, choices=[('12M', '12 Meses'), ('18M', '18 Meses'), ('24M', '24 Meses'), ('36M', '36 Meses')], max_length=3, null=True, verbose_name='Duración de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='nombre_prop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='pais',
            field=models.CharField(blank=True, choices=[('GTM', 'Guatemala'), ('PAN', 'Panamá'), ('SLV', 'El Salvador'), ('HND', 'Honduras'), ('BLZ', 'Belize'), ('NIC', 'Nicaragua'), ('CRI', 'Costa Rica'), ('OTR', 'Otro')], max_length=3, verbose_name='País'),
        ),
    ]
