# Generated by Django 3.2.6 on 2021-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0036_auto_20210820_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='codigo_org',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código de organización'),
        ),
        migrations.AlterField(
            model_name='coparte',
            name='codigo_org',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código de organización'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='codigo_org',
            field=models.CharField(max_length=25, unique=True, verbose_name='Código de organización'),
        ),
    ]
