# Generated by Django 3.2.6 on 2021-08-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0038_auto_20210820_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoyoestrategico',
            options={'verbose_name': 'Apoyo Estratégico', 'verbose_name_plural': 'Apoyos estratégicos'},
        ),
        migrations.AlterModelOptions(
            name='informefinal',
            options={'verbose_name_plural': 'Informes finales'},
        ),
        migrations.AlterModelOptions(
            name='informeic',
            options={'verbose_name': 'Informe iniciativa conjunta', 'verbose_name_plural': 'Informes iniciativas conjuntas'},
        ),
        migrations.AlterModelOptions(
            name='informeintermedio',
            options={'verbose_name_plural': 'Informes intermedios'},
        ),
        migrations.AlterModelOptions(
            name='propuestaic',
            options={'verbose_name': 'Propuesta iniciativa conjunta', 'verbose_name_plural': 'Propuestas iniciativas conjuntas'},
        ),
        migrations.RenameField(
            model_name='informefinal',
            old_name='informe_intermedios_anterior',
            new_name='informe_intermedio_anterior',
        ),
    ]
