# Generated by Django 3.2.6 on 2021-08-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0039_auto_20210823_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeic',
            name='prop_ic_vincula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.propuestaic'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='participa_ic',
            field=models.CharField(blank=True, choices=[('IC1', 'INICIATIVA-3'), ('IC2', 'GAGGA'), ('IC3', 'IMDEFENSORAS')], max_length=3, null=True, verbose_name='Iniciativa conjunta en la que participa'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='programa',
            field=models.CharField(blank=True, choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, null=True, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='tipo_ic',
            field=models.CharField(blank=True, choices=[('SCA', 'Socias en Centroamérica'), ('FCA', 'Socias fuera de Centroamérica'), ('RFM', 'Redes y fondos de mujeres'), ('RRC', 'Respuesta Rápida en Centroamérica'), ('RRF', 'Respuesta Rápida fuera de Centroamérica'), ('OTR', 'Otros')], max_length=3, null=True, verbose_name='Tipo de iniciaptiva conjunta'),
        ),
        migrations.AlterField(
            model_name='propuestaic',
            name='ic_vinculada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.iniciativaconjunta', verbose_name='Iniciativa conjunta vinculada'),
        ),
    ]
