# Generated by Django 3.2.6 on 2021-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0040_auto_20210824_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeic',
            name='codigo_inf_ic',
            field=models.CharField(max_length=25, null=True, verbose_name='Informe de IC'),
        ),
    ]
