# Generated by Django 3.2.6 on 2021-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0041_alter_informeic_codigo_inf_ic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='ano_donativo',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año del donativo'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='apoyos_estra_punt',
            field=models.CharField(blank=True, choices=[('BEV', 'Becas para eventos'), ('PEP', 'Proyectos estratégicos puntuales'), ('AOC', 'Apoyo a organizaciones en crisis financiera'), ('DOP', 'Donativos patrocinados')], max_length=3, null=True, verbose_name='Apoyos Estratégicos Puntuales'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='fondo_resp_emer',
            field=models.CharField(blank=True, choices=[('PDD', 'Protección a defensoras de derechos humanos'), ('APE', 'Apoyo de emergencia a organizaciones, redes y articulaciones'), ('RDN', 'Respuesta ante desastres naturales'), ('CLD', 'Cambios legislativos que afectan derechos de las mujeres')], max_length=3, null=True, verbose_name='Fondos de Respuesta a Emergencias'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='programa',
            field=models.CharField(blank=True, choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, null=True, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='tipo_donativo',
            field=models.CharField(blank=True, choices=[('FRE', 'Fondos de Respuesta a Emergencias'), ('AEP', 'Apoyos Estratégicos Puntuales')], max_length=3, null=True, verbose_name='Tipo de donativo'),
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='tipo_org',
            field=models.CharField(blank=True, choices=[('BEV', 'Grupo o colectivo de base'), ('PEP', 'Organizaciones grandes'), ('AOC', 'INGO/ONG internacional'), ('DOP', 'Grupos intermedios'), ('BEV', 'Redes'), ('PEP', 'Fondos'), ('AOC', 'Defensora de derechos humanos')], max_length=3, null=True, verbose_name='Tipo de organización'),
        ),
    ]
