# Generated by Django 3.2.6 on 2021-09-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0042_auto_20210824_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coparte',
            options={'verbose_name_plural': '1. Copartes'},
        ),
        migrations.AlterModelOptions(
            name='grupoactor',
            options={'verbose_name': 'Actor o grupo', 'verbose_name_plural': 'Actores o grupos'},
        ),
        migrations.AlterModelOptions(
            name='informefinal',
            options={'verbose_name_plural': '4. Informes finales'},
        ),
        migrations.AlterModelOptions(
            name='informeic',
            options={'verbose_name': 'Informe iniciativa conjunta', 'verbose_name_plural': '7. Informes iniciativas conjuntas'},
        ),
        migrations.AlterModelOptions(
            name='informeintermedio',
            options={'verbose_name_plural': '3. Informes intermedios'},
        ),
        migrations.AlterModelOptions(
            name='iniciativaconjunta',
            options={'verbose_name': 'Iniciativa conjunta', 'verbose_name_plural': '5. Iniciativas conjuntas'},
        ),
        migrations.AlterModelOptions(
            name='propuesta',
            options={'verbose_name_plural': '2. Propuestas'},
        ),
        migrations.AlterModelOptions(
            name='propuestaic',
            options={'verbose_name': 'Propuesta iniciativa conjunta', 'verbose_name_plural': '6. Propuestas iniciativas conjuntas'},
        ),
        migrations.AddField(
            model_name='propuestaic',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AddField(
            model_name='propuestaic',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cuerpo',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='iniciativaconjunta',
            name='tipo_ic',
            field=models.CharField(choices=[('SCA', 'Socias en Centroamérica'), ('FCA', 'Socias fuera de Centroamérica'), ('RFM', 'Redes y fondos de mujeres'), ('RRC', 'Respuesta Rápida en Centroamérica'), ('RRF', 'Respuesta Rápida fuera de Centroamérica'), ('OTR', 'Otros')], max_length=3, null=True, verbose_name='Tipo de iniciaptiva conjunta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='duracion_prop',
            field=models.CharField(choices=[('12M', '12 Meses'), ('18M', '18 Meses'), ('24M', '24 Meses'), ('36M', '36 Meses')], max_length=3, null=True, verbose_name='Duración de la propuesta'),
        ),
    ]
