# Generated by Django 3.2.6 on 2021-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0043_auto_20210902_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeic',
            name='sello_fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sello fecha de actualización'),
        ),
        migrations.AddField(
            model_name='informeic',
            name='sello_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sello fecha de creación'),
        ),
    ]
