# Generated by Django 3.2.7 on 2021-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0044_auto_20210902_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoyoestrategico',
            options={'verbose_name': '8. Apoyo Estratégico', 'verbose_name_plural': '8. Apoyos estratégicos'},
        ),
        migrations.AlterField(
            model_name='apoyoestrategico',
            name='programa',
            field=models.CharField(choices=[('AFP', 'AfroPoderosas'), ('DMJ', 'Derechos de las Mujeres y Justicia Ambiental'), ('DLM', 'Derechos Laborales de las Mujeres'), ('DSR', 'Derechos Sexuales y Reproductivos'), ('LDS', 'Liderando desde el Sur'), ('MDC', 'Mujeres con Discapacidad'), ('MMJ', 'Mujeres jóvenes'), ('MMM', 'Mujeres Migrantes'), ('PEG', 'Programa Especial Guatemala'), ('NIN', 'Ninguno')], max_length=3, null=True, verbose_name='Programa'),
        ),
    ]
