# Generated by Django 3.2.6 on 2021-08-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0019_informeic_propuestaic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, null=True, verbose_name='Código')),
                ('ano', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año')),
                ('coparte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.coparte')),
            ],
        ),
        migrations.CreateModel(
            name='AutoevaluacionCoparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, null=True, verbose_name='Código')),
                ('ano', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True, verbose_name='Año')),
                ('coparte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.coparte')),
            ],
        ),
    ]
